name: Deploy to Simply.com via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.simply.com
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftp
          server-dir: /
          dangerous-clean-slate: false
